### ISSUE TITLE
Clarification on req.clearTimeout()

### ISSUE THREAD

**Issue by mrodrig** [expressjs/timeout#15]
Hi,

I was just looking for some clarification on the req.clearTimeout() function -- does it reset the timeout (ie. start the timeout counter from 0) or does it stop `connect-timeout` from monitoring the request for a timeout?  I wasn't sure based on the info in the README.

Thanks in advance!

Mike

**Comment by dougwilson** [comment]
It removes the timeout completely an is analogous to the `clearTimeout` function in JavaScript. I can add more description rather than relying on the similar name to communicate the functionality :)

**Comment by mrodrig** [comment]
Awesome, thanks! That's exactly what I was looking for.
