### ISSUE TITLE
Can't set headers after they are sent.

### ISSUE THREAD

**Issue by jwerre** [expressjs/timeout#17]
Pardon me if this has been asked a million time but It's not clear how to best handle timeouts. The following script will crash the server since `res.send` is called after the timeout. I could wrap `res.send` in an `if !res.headersSent` but it seems a little excessive to do that for every route. I'm not sure how to best handle this situation.

    var express = require('express');
    var timeout = require('connect-timeout');

    var handleTimeout = function (req, res, next) {
        if (!req.timedout) next();
    };

    var app = express()
        .use(timeout(500))
        .use(handleTimeout)
        .get("/", function (req, res, next) {
            setTimeout(function () {
                // This causes "Error: Can't set headers after they are sent."
                res.send({peaches:"yummy", turnips:"yucky"}); 
            }, 1000);
        })
        .use(handleTimeout)
        .listen(8888, function(){
                console.log('Server started on port 8888');
            });

Error:

    Starting child process with 'node timeout.js'
    Server started on port 8888
    ServiceUnavailableError: Response timeout
        at IncomingMessage.<anonymous> (/Users/jw/Desktop/timeout/node_modules/connect-timeout/index.js:69:8)
        at IncomingMessage.emit (events.js:95:17)
        at null._onTimeout (/Users/jw/Desktop/timeout/node_modules/connect-timeout/index.js:41:11)
        at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

    http.js:689
        throw new Error('Can\'t set headers after they are sent.');
              ^
    Error: Can't set headers after they are sent.
        at ServerResponse.OutgoingMessage.setHeader (http.js:689:11)
        at ServerResponse.header (/Users/jw/Desktop/timeout/node_modules/express/lib/response.js:718:10)
        at ServerResponse.send (/Users/jw/Desktop/timeout/node_modules/express/lib/response.js:163:12)
        at ServerResponse.json (/Users/jw/Desktop/timeout/node_modules/express/lib/response.js:249:15)
        at ServerResponse.send (/Users/jw/Desktop/timeout/node_modules/express/lib/response.js:151:21)
        at null._onTimeout (timeout/timeout.js:13:17)
        at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
    Program node timeout.js exited with code 8

**Comment by dougwilson** [comment]
> I could wrap res.send in an if !res.headersSent but it seems a little excessive to do that for every route. I'm not sure how to best handle this situation.

There are two solutions:

1. You can do as you suggest: check if the request timed out once your timer fired.
2. When you set your timeout, also add a listener on the `timeout` event and then clear the timeout so your timer never even fires:
```js
    .get("/", function (req, res, next) {
        var timer = setTimeout(function () {
            // This causes "Error: Can't set headers after they are sent."
            res.send({peaches:"yummy", turnips:"yucky"}); 
        }, 1000);
        req.once('timeout', function () {
          clearTimeout(timer);
        });
    })
```

**Comment by 8026787** [comment]
I've solved it this way:

Override res.send in the very first middleware:
```
app.use(function(req,res,next){
    var _send = res.send;
    var sent = false;
    res.send = function(data){
        if(sent) return;
        _send.bind(res)(data);
        sent = true;
    };
    next();
});
```

**Comment by josieusa** [comment]
@romanesko thanks for your code, here is how I edited it in order to use `res.locals`:

    app.use(function(req, res, next) {
      const _end = res.end;
      res.locals._sent = false;
      res.end = function(data) {
        if (res.locals._sent) return;
        _end.bind(res)(data);
        res.locals._sent = true;
      };
      next();
    });
      next();
    });

**Comment by sdiptapaul** [comment]
life saver @romanesko

**Comment by justswim** [comment]
@romanesko This doesn't seem to work for me, sent never gets set to true. Is there a specific place where I need to put the function?

**Comment by hakkisabah** [comment]
@romanesko its great! its realy life saver.

**Comment by phuongvu0203** [comment]
@romanesko yup...you're life safer

**Comment by ani-naslyan** [comment]
Try to use return statement before sending the result back with res.send().
https://teamtreehouse.com/community/hi-im-getting-a-cant-set-headers-after-they-are-sent-trying-to-send-a-ressend
