### ISSUE TITLE
clearer documentation

### ISSUE THREAD

**Issue by kevinburkeshyp** [expressjs/timeout#18]
I am looking for something that will actually halt processing requests which take beyond a certain amount of time - e.g. the CPU will stop executing any commands for that request. As far as I can tell the library simply fires the given callback when requests take longer than the given amount but does not do anything to cancel or halt execution of that request.

Assuming the latter is close to impossible in node, but it would be great if the README for this library would be clearer on this point.

**Comment by dougwilson** [comment]
I thought it was clear, but I guess not? It's hard to think of a way to make it clear for you, so a PR to us with what text changes you think will help clarity would be most welcome :)

**Comment by dougwilson** [comment]
I looked and the package's description itself was not great, so I made it more explicit the module is for Connect/Express frameworks. Please feel free to offer up a PR at anytime with suggested wording changes, though, and we can look over it :) The biggest problem we have is what can sound clear to us doesn't mean it sounds clear to you, so getting your suggested wording it the only way we can know what would make it clear for you :)

**Comment by kevinburkeshyp** [comment]
maybe something like

> While the library will emit a `'timeout'` event when requests exceed the given timeout, node will continue processing the request until execution completes. Requests will continue to use CPU and memory even if you are returning a HTTP response in the `timeout` callback. For better control over CPU/memory, you may need to find the events that are taking a long time (3rd party HTTP requests, disk I/O, database calls) and find a way to cancel them, and/or close the attached sockets.

?

**Comment by dougwilson** [comment]
Hi @kevinburkeshyp , sorry, I missed your comment somehow! I went ahead and added it verbatim to the readme, with you as the author :) If you would like me to remove you as the author of the comment, just let me know, but I want to give you credit :)!
