### ISSUE TITLE
'connect-timeout' is possibly misleading

### ISSUE THREAD

**Issue by kevinburkeshyp** [expressjs/timeout#19]
I would expect a library named `connect-timeout` to enable the ability to time out a socket CONNECT request - something I believe that [the node `request` library does not currently offer](https://github.com/request/request/issues/1660), for example. I was surprised to learn it had more to do with timing out app requests.

**Comment by dougwilson** [comment]
This module comes from a long time ago, where everything connect-* was for the connect web framework. Changing a module's name is not trivial and of course all it will do is make two modules on npm: connect-timeout and whatever the new name is. Npm does not offer the ability to rename modules.

**Comment by kevinburkeshyp** [comment]
Fair enough! Yeah I don't know what would be better besides just merging support into the places that should have it
