### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by sachi-pen** [expressjs/timeout#29]
For easier understanding, kindly add to documentation that this middleware does not override the server's default timeout. 

In case of the setting timeouts greater than the default of 120000 ms, the usage shall be as below
```js
var express = require('express')
var timeout = require('connect-timeout')

var app = express();

let SERVER_TIMEOUT = 300000;
app.use(timeout((SERVER_TIMEOUT/1000)+"s"))

//Routers here
let server = app.listen(3000);
server.timeout = SERVER_TIMEOUT;
```
(or)

other better examples.

It could just save a lot of time for the beginners.

**Comment by dougwilson** [comment]
Hi! Thanks for the feedback. Writing good doximentation is hard, especially when the person writing it takes their own knowledge for granted and it becomes blinders, not even realizing there is something a prospective user may not know. Sorry for the pain you went though. I'm not sure how to make it better, but maybe would you be willing to make a pull request with your thoughts on the changes that would have helped you through the journey you had?

**Comment by renanpupin** [comment]
In that case why is it also necessary to set "server.timeout"?

**Comment by celalo** [comment]
> In that case why is it also necessary to set "server.timeout"?

node.js default (http) server timeout is 120 sec. Requests would hit this limit before connect-timeout's limit.

**Comment by TikiLobel** [comment]
I noticed that in one of my CentOS Linux 7 environments (Not all of them), the following does **not** have any effect over the default 30 second express timeout:
`app.use(timeout(90000))`
Where as the following **does** have an effect:
`app.use(timeout('90s'))`

Versions:
express: `^4.15.1`
connection-timeout: `1.9.0`
Node: `8.12.0`
npm: `6.4.1`

In the documentation it says both argument formats should work (As it does in most of my environments). 
Is there any other reason that the first format should not work?

Thanks!

**Comment by UlisesGascon** [comment]
PR #30 was closed ([Link for extra context](https://github.com/expressjs/timeout/pull/30#issuecomment-612727346)), same for this issue.
