### ISSUE TITLE
What is the associate between this library and http's timeout

### ISSUE THREAD

**Issue by iamnotstone** [expressjs/timeout#32]
I noticed that the node.js's native http also have a timeout.  And I do understand that timeout is about socket connection during it's inactive . And now, this library is about a http request . So I'm wondering what will happen if the value of expreejs/timeout is large then http's timeout ?

**Comment by dougwilson** [comment]
If the value is larger, then when the timeout will trigger for this module, the socket will likely already have been closed by Node.js.
