### ISSUE TITLE
Turning off response timeouts

### ISSUE THREAD

**Issue by hexad** [expressjs/timeout#35]
I have a long running job and i want to turn off the response timeout.

The only thing somehwat relevant i found is this:

> req.clearTimeout()
Clears the timeout on the request. The timeout is completely removed and will not fire for this request in the future.

Here it mentions requests. Can i remove the timeout on the response of the server?

**Comment by dougwilson** [comment]
It clears the only timer this module sets.

**Comment by dougwilson** [comment]
Closing since I haven't heard anything back :+1:
