### ISSUE TITLE
Make timeout action more flexible

### ISSUE THREAD

**Issue by amazzoccone** [expressjs/timeout#36]
Actually it's impossible to change the response generated when timeout occurs.
This limitation does not allow the package to be integrated with **Apollo Server** for example.

It could be cool to has an option to change the default behaviour:
```
cb(createError(503, 'Response timeout', {
      code: 'ETIMEDOUT',
      timeout: delay
    }))
```

**Comment by amazzoccone** [comment]
Any resolution? @erperejildo

**Comment by amazzoccone** [comment]
Any resolution? @dougwilson

**Comment by dougwilson** [comment]
Hi @amazzoccone what kind of customization are looking for? The code you posted above is when you have `respond: true` (the default) option. All it does is generate an error object, at which point you can add an error-handling middleware to write the response however you like. This module never writes anything directly to the response, in fact.

That error just provide your error handler with some information to assist in generating your desired output. For more information on how to create an error handler: http://expressjs.com/en/guide/error-handling.html

Here is an example:

```js
app.use(timeout('1m'))

// ... things

app.use(function (err, req, res, next) {
  if (err.code !== 'ETIMEDOUT') return next(err) // this only handles writing timeouts
  // ... now write out the timeout response
})
```

**Comment by dougwilson** [comment]
You can also set `respond: false` option and just add a listener to the `timeout` event to handle the response as you like:
```js
app.use(timeout('1m', { respond: false }))

// order between these doesn't matter

app.use(function (req, res, next) {
  req.once('timeout', function () {
    // ... now write out the timeout response
  })
  next()
})
```

**Comment by amazzoccone** [comment]
Thanks for all the information! 🙌 
I will try to implement it in the _Apollo Server_ project using the `respond` option as `false`.
