### ISSUE TITLE
Source code was not found

### ISSUE THREAD

**Issue by erperejildo** [expressjs/timeout#37]
Getting this error on Sentry:

![capture](https://user-images.githubusercontent.com/5629919/52797198-ae97c680-3075-11e9-8041-fd6669eb4da0.PNG)

Everything works perfect on my local

**Comment by dougwilson** [comment]
What is Sentry?

**Comment by erperejildo** [comment]
just a platform to track and fix errors in real time. Let's say I get that on production and not locally

**Comment by dougwilson** [comment]
So just as a general answer,  how are you copying files to production? Perhaps that process is accidentally missing that file during the copy ? It could miss other just that os the first error and is bailing out.

I would start investigating the process that is being used to copy files up to check if that file is being included or not.

**Comment by dougwilson** [comment]
Closing as stale.
